name: Build, Test, and Push semantic-release-offline Image

on:
  push:
    branches: 
      - main
      - release/*
  # pull_request:
  #   branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
    
    # Login to Private DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # Build the Docker image
    - name: Build semantic-release-offline image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false # Do not push yet, we will test the image first
        tags: semantic-release-offline:test
    
    # Test the Docker image
    - name: Test semantic-release-offline image
      run: |
        docker run --rm semantic-release-offline:test semantic-release --version
    
    # Push the Docker image to DockerHub
    - name: Push semantic-release-offline image
      if: success() # Only push if the build and test steps succeed
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/semantic-release-offline:v1.0